## NOTE: Generated by AI - Claude Opus 4.6

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

def draw_matching_diagram():
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    ax.axis("off")
    ax.set_title("Column Matching Between Datasets", fontsize=14, fontweight="bold")

    # Dataset A columns
    a_cols = ["TotalPop", "MedAge", "FamHH", "Detached", "pctDetach", "Kerosene_moe"]
    b_cols = ["MedAge", "FamHH", "Detached", "pctDetach", "TotalPop", "pctBachelors", "GradProf"]

    ax.text(1.5, 5.5, "Dataset A", ha="center", fontsize=12, fontweight="bold")
    ax.text(8, 5.5, "Dataset B", ha="center", fontsize=12, fontweight="bold")

    a_color = "#E8F0FE"
    b_color = "#FFF3E0"
    match_color = "#C8E6C9"

    # Draw A columns
    for i, col in enumerate(a_cols):
        y = 4.8 - i * 0.7
        matched = col in b_cols
        c = match_color if matched else a_color
        rect = mpatches.FancyBboxPatch((0.2, y - 0.2), 2.6, 0.45, boxstyle="round,pad=0.1",
            facecolor=c, edgecolor="#666")
        ax.add_patch(rect)
        ax.text(1.5, y, col, ha="center", va="center", fontsize=9)

    # Draw B columns
    for i, col in enumerate(b_cols):
        y = 4.8 - i * 0.7
        matched = col in a_cols
        c = match_color if matched else b_color
        rect = mpatches.FancyBboxPatch((6.5, y - 0.2), 2.6, 0.45, boxstyle="round,pad=0.1",
            facecolor=c, edgecolor="#666")
        ax.add_patch(rect)
        ax.text(8, y, col, ha="center", va="center", fontsize=9)

    # Draw match lines
    for a_col in a_cols:
        if a_col in b_cols:
            a_y = 4.8 - a_cols.index(a_col) * 0.7
            b_y = 4.8 - b_cols.index(a_col) * 0.7
            ax.annotate("", xy=(6.5, b_y), xytext=(2.8, a_y),
                arrowprops=dict(arrowstyle="-", color="#4CAF50", lw=1.5, connectionstyle="arc3,rad=0.1"))

    # Legend
    ax.add_patch(mpatches.FancyBboxPatch((3.3, 0.3), 0.3, 0.3, boxstyle="round,pad=0.05",
        facecolor=match_color, edgecolor="#666"))
    ax.text(3.8, 0.45, "= Shared (used for matching)", va="center", fontsize=8)

    ax.add_patch(mpatches.FancyBboxPatch((3.3, 0.8), 0.3, 0.3, boxstyle="round,pad=0.05",
        facecolor=b_color, edgecolor="#666"))
    ax.text(3.8, 0.95, "= Extra (merged into output)", va="center", fontsize=8)

    ax.add_patch(mpatches.FancyBboxPatch((3.3, 1.3), 0.3, 0.3, boxstyle="round,pad=0.05",
        facecolor=a_color, edgecolor="#666"))
    ax.text(3.8, 1.45, "= Target only (kept in output)", va="center", fontsize=8)

    plt.tight_layout()
    plt.savefig("data/matching_diagram.png", dpi=150, bbox_inches="tight")
    print("Matching diagram saved to data/matching_diagram.png")

if __name__ == "__main__":
    draw_matching_diagram()
