name: Python tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up uv with Python 3.10
      uses: astral-sh/setup-uv@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: python
      run: uv sync
    - name: Test with unittest
      working-directory: python
      run: uv run python -m unittest discover tests
